<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Principal extends Seeder
{
    public function run()
    {
        $datalist = array(
            'PT MANDALA PUTERA PRIMA',
            'PT MAJU MUKTI JAYA',
            'PT JAYA KARYA PASUNDAN',
            'PT INFITECH SOLUSI INDONESIA',
            'PT INDONESIA FERRY PROPERTI',
            'PT HUTAMA MANGGALA PERSADA',
            'PT HARMONI PRIMA MEDIKA',
            'PT HANWHA LIFE INSURANCE INDONESIA',
            'PT GALUNG SOLUSI BANGUN TEKNIK',
            'PT FIBERHOME TECHNOLOGIES INDONESIA',
            'PT ENDAVO CITA PERKASA',
            'PT DUA BINTANG PANEL',
            'PT DINAYA SEJAHTERA ABADI',
            'PT DINAMIKA ENERGI MARITIM',
            'PT DHARMA HUTAMA KARYA',
            'PT CITRA GUMILANG PRATAMA',
            'PT BONI CIPTA',
            'PT BINTANG MILENIUM PERKASA',
            'PT BINA MUDA SEJAHTERA',
            'PT TELEKOMUNIKASI INDONESIA (PERSERO) Tbk',
            'PT TECHNOLOGY KARYA MANDIRI',
            'PT TANATO MAKMUR LESTARI',
            'PT TAMA TELEMATIKA NUSANTARA',
            'PT SURYA MANUEL UTAMA',
            'PT SINAR LAUT DUA',
            'PT SINAR KENCANA INDAH',
            'PT SARANA KOMUNIKASI PERTIWI',
            'PT RAPIK KARYA MANDIRI',
            'PT PELITA KARYA PERKASA',
            'PT PALAPA TIMUR TELEMATIKA',
            'PT NUSANTARA TELEMATICS SYSTEMS',
            'PT MULTIFILING MITRA INDONESIA Tbk',
            'PT MULTI GRAHA TEKNIKA',
            'PT MORASHA INTI SHABIRA',
            'PT MORA TELEMATIKA INDONESIA',
            'PT MITRA SISTEMATIKA GLOBAL',
            'PT MEGAYASA ENGINEERING',
            'PT ANUGERAH SULTAN TEKNIK',
            'PT ANSINDA COMMUNICATION INDONESIA',
            'PT ALUPHI HIJAU LUMINA',
            'PT ALPHA CENTAURI INTERNATIONAL',
            'PT ALMAGA TALENTA TEKNOLOGI',
            'PT ADYAWINSA TELECOMMUNICATION & ELECTRICAL',
            'CV ZAHARA PERTIWI',
            'CV WIRA UTAMA',
            'CV WINNATAMA MANDIRI',
            'CV WINDU AGUNG JAYA',
            'CV VIRGO ADITAMA',
            'CV UNIVERSA INDOTAMA',
            'CV TUNAS RAYA ABADI',
            'CV TRI ANGELICA PUTRI',
            'CV TIOMIN SIMON',
            'CV TATA MULTI KONSTRUKSI',
            'CV TAPANULI KARYA',
            'CV SRI REJEKI SEJAHTERA',
            'CV SRI OKTAPIANI AGUNG',
            'CV SKALA RAYYA',
            'CV SAYAGA MANDRAGUNA',
            'CV SATRIA PRATAMA KONSTRUKSI',
            'CV SARIMAS PUTRA ANDALAS',
            'CV SAPTA PRIMA UTAMA',
            'CV RIZKI JAYA CONSTRUCTION',
            'CV RINA LESTARI',
            'CV RATUMAS TEKNIKINDO',
            'CV RAJA BANGUN PRADANA',
            'CV PUTRA TANOTUR',
            'CV PUTRA TAMSUNG SIGUMPAR',
            'CV PIRMA MANDIRI',
            'CV PERMATA QIARA UTAMA',
            'CV PARUNG BINGUNG SEJAHTERA',
            'CV NOVITAMA SUKSES MANDIRI',
            'CV NINDYA UTAMA MANDIRI',
            'CV NIKITA LUMBAN BUTAR',
            'CV MULIARAJA SEJAHTERA'
        );
    }
}
